repository: git@github.com:foxycode/foe-tips.git

platforms:
  production:
    default_branch: master
    max_releases: 3
    servers:
      jacik.cz:
        host: jacik.cz
        user: foe
        ssh_key: deploy.key
        path: /apps/foe/www

shared_files:
  - app/Config/config.local.neon

shared_folders:
  - var/log

on_deploy:
  - "composer install --no-interaction --no-progress --no-suggest --no-dev --optimize-autoloader"

post_deploy:
  - "bin/console orm:generate-proxies -q"
